// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwynVOHGnlfWyEkYR0HH3rhzzPp7h4Slo',
    appId: '1:305329613273:web:d9348cda1006b40ca051c8',
    messagingSenderId: '305329613273',
    projectId: 'testproject-99d69',
    authDomain: 'testproject-99d69.firebaseapp.com',
    storageBucket: 'testproject-99d69.firebasestorage.app',
    measurementId: 'G-54N98SH8QQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXRzc56Cs8GgICdi-_0Kxie_krJXJCMX4',
    appId: '1:305329613273:android:d140ad1cb9c8824ca051c8',
    messagingSenderId: '305329613273',
    projectId: 'testproject-99d69',
    storageBucket: 'testproject-99d69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_xW-t4fQy4U02i4zLHus5og0xTWcuXkE',
    appId: '1:305329613273:ios:0b73be277ddde4f9a051c8',
    messagingSenderId: '305329613273',
    projectId: 'testproject-99d69',
    storageBucket: 'testproject-99d69.firebasestorage.app',
    iosBundleId: 'com.sevaexchange.app',
  );
}
